openapi: 3.0.0
info:
  title: Azure Blob Storage API
  description: API pour gérer les fichiers sur Azure Blob Storage.
  version: "1.0.0"

servers:
  - url: http://localhost:3000
    description: Serveur local

paths:
  /upload:
    post:
      summary: Télécharger un fichier sur Azure Blob Storage
      description: Permet de télécharger un fichier vers un conteneur Azure Blob Storage.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Le fichier à télécharger.
      responses:
        "200":
          description: Fichier téléchargé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Fichier téléchargé avec succès"
                  fileUrl:
                    type: string
                    example: "https://nifnet.blob.core.windows.net/media/12345-fichier.txt"
        "400":
          description: Erreur de requête
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Le fichier est requis."
        "500":
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Erreur lors du téléchargement sur Azure."

components:
  schemas:
    UploadFileResponse:
      type: object
      properties:
        message:
          type: string
        fileUrl:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
