openapi: 3.0.0
info:
  title: API Documentation
  description: API pour gérer les utilisateurs, contenus, médias, commentaires et notifications.
  version: "1.0.0"

servers:
  - url: https://nfi-mondial-net-guhdd8fhcxgxh7gz.northeurope-01.azurewebsites.net
    description: Serveur principal

paths:
  /utilisateurs:
    post:
      summary: Créer un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                email:
                  type: string
                motDePasse:
                  type: string
      responses:
        "201":
          description: Utilisateur créé
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        "200":
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nom:
                      type: string

  /contenus/create:
    post:
      summary: Créer un contenu avec un média
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                media:
                  type: string
                  format: binary
                titre:
                  type: string
      responses:
        "201":
          description: Contenu créé

  /commentaires:
    post:
      summary: Ajouter un commentaire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contenuId:
                  type: integer
                texte:
                  type: string
      responses:
        "201":
          description: Commentaire ajouté

  /notifications/{user_id}:
    get:
      summary: Récupérer les notifications non lues
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Notifications récupérées

  /notifications/{notification_id}/read:
    put:
      summary: Marquer une notification comme lue
      parameters:
        - name: notification_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Notification marquée comme lue
